// auto-generated by: bella secrets generate dart --types
// project: awesome/dev
// generated: 2026-03-14 20:24:59 UTC
// DO NOT edit manually — re-run bella secrets generate dart --types to update.
import 'dart:io';

class AwesomeSecrets {
  final Map<String, String>? _map;

  /// Env-var mode: reads from [Platform.environment] (injected by `bella run`).
  AwesomeSecrets() : _map = null;
  AwesomeSecrets._fromSecrets(this._map);

  /// SDK mode: use with [BellaClient.pullSecretsAs].
  ///
  /// ```dart
  /// final client = BellaClient.fromEnv();
  /// final s = await client.pullSecretsAs(AwesomeSecrets.fromMap);
  /// print(s.someKey); // typed
  /// ```
  factory AwesomeSecrets.fromMap(Map<String, String> secrets) =>
      AwesomeSecrets._fromSecrets(secrets);

  String _require(String key) {
    final v = _map != null ? _map![key] : Platform.environment[key];
    if (v == null) throw Exception('Required secret "$key" is not set.');
    return v;
  }

  /// Number of secrets in the pulled map (SDK mode only; 0 in env-var mode).
  int get secretCount => _map?.length ?? 0;

  String get appConfig => _require("APP_CONFIG");
  String get appId => _require("APP_ID")  /* UUID */;
  String get connectionstringsPostgres => _require("ConnectionStrings__Postgres");
  String get databaseUrl => _require("DATABASE_URL");
  bool get enableFeatures => _require("ENABLE_FEATURES") == "true";
  String get externalApiKey => _require("EXTERNAL_API_KEY");
  /// Gleap service
  String get gleapApiKey => _require("GLEAP_API_KEY");
  int get port => int.parse(_require("PORT"));
}
